name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Show current directory and files
        run: |
          pwd
          ls -al

      - name: Debugging SSH connection
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          echo "REMOTE_HOST: $REMOTE_HOST"
          echo "REMOTE_USER: $REMOTE_USER"
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts || { echo 'ssh-keyscan failed' ; exit 1; }
          cat ~/.ssh/known_hosts
          ssh -vvv -p5983 $REMOTE_USER@$REMOTE_HOST 'echo "SSH connection successful"' || { echo 'SSH connection failed' ; exit 1; }

      - name: Deploy to Server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          ssh -p5983 $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd /servertestcmg &&
            git pull origin main &&
            npm install &&
            npm run build &&
            pm2 restart tu-app
          EOF
