name: Deploy to Server

on:
  push:
    branches:
      - main # Puedes cambiar esto a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # Cambia esto según el gestor de paquetes que utilices

      - name: Build the project
        run: npm run build # Cambia esto según el script de build que utilices

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/" # Cambia esto según tu directorio de build
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/path/to/your/deployment/directory" # Cambia esto según la ruta en tu servidor
